### ISSUE TITLE
How does this overlap with Reactive.jl?

### ISSUE THREAD

**Issue by timholy** [yuehhua/ReactiveExtensions.jl#2]
Link: https://github.com/JuliaGizmos/Reactive.jl

**Comment by yuehhua** [comment]
They are similar, but not the same.
For reactive programming, I expect the way to chaining things up, and it can be something like the following.

```
foo = from([1,2,3,4,5]).map(x -> x + 1).tolist()
```

But the [Reactive.jl](https://github.com/JuliaGizmos/Reactive.jl) is not in this way.
It separate the steps line by line.
If I follow the way, I will get the code hard to read.
Rather, I think the [RxPY](https://github.com/ReactiveX/RxPY) can provide better readability.

So far, due to the syntax, I came up with the way to chain things up is:

```
foo = from([1,2,3,4,5])(map, x -> x + 1)
to_list(foo)
```

**Comment by timholy** [comment]
Not sure I quite follow your example, but isn't it something like `value(map(x->x+1, Signal([1,2,3,4,5])))`?

**Comment by yuehhua** [comment]
Yes, it's the same operation, but not the same readability.
If you chain more than 3 operations, the code will getting harder to read.

**Comment by timholy** [comment]
`map(Signal([1,2,3,4,5])) do x x+1 end`

**Comment by timholy** [comment]
(Sorry, hit the wrong button)

**Comment by yuehhua** [comment]
Uh........
What if?

```
from([1,2,3,4,5])
.map(x -> x + 1)
.filter(x -> x < 5)
.reduce((x, y) -> x + y)
```

**Comment by yuehhua** [comment]
Oh! Maybe I can add this feature to [Reactive.jl](https://github.com/JuliaGizmos/Reactive.jl)?
One can write it in different style.
It would be exhausted to develop a package from the ground up.

**Comment by timholy** [comment]
Right. Generally it's not good for the community to have 2 packages which do almost exactly the same thing but with slightly different syntax.

**Comment by yuehhua** [comment]
So, can you introduce me into it or I can just fork it?

**Comment by yuehhua** [comment]
Add features to [Reactive.jl](https://github.com/JuliaGizmos/Reactive.jl).
